# Generated by Django 4.2.3 on 2023-07-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_react', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
